spring:
  application:
    name: zstore-oder
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    instance-id: 192.168.0.133:9002
    ip-address: 192.168.0.133
debug: true
