spring:
  application:
    name: zstore-user
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    instance-id: 192.168.0.133:9001
    ip-address: 192.168.0.133
debug: true
